export const COUNTER_ACTION_INCREMENT = "INCREMENT";
export const COUNTER_ACTION_DECREMENT = "DECREMENT";
export const COUNTER_ACTION_ACTIVATE_AUTOINCREMENT = "ACTIVATE_AUTO_INCREMENT";
export const COUNTER_ACTION_DEACTIVATE_AUTOINCREMENT =
  "DEACTIVATE_AUTO_INCREMENT";
